### ISSUE TITLE
Require statement incorrect in readme

### ISSUE THREAD

**Issue by duncantmiller** [dickdavis/anthropic-rb#17]
In the readme it says to require the gem with `require 'anthropic-rb'`. 

```
require 'anthropic-rb'

Anthropic.setup do |config|
  config.api_key = 'YOUR_API_KEY'
end
```

But this raises an error:

```
rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- anthropic-rb (LoadError)
```

Instead, I believe it needs to be `require 'anthropic'` so:

```
require 'anthropic'

Anthropic.setup do |config|
  config.api_key = 'YOUR_API_KEY'
end
```

Which checks out since that is what the file name is in the repo.

**Comment by dickdavis** [comment]
Thanks for the catch! I'll make the update.
